#!/usr/bin/env python3
"""bench/capture_patterns.py (T-89) — two-pattern end-to-end demo capture.

Runs a single MOCK `triage short.log` and records the full xv6 console
transcript to docs/patterns_demo.txt, evidencing BOTH Liberal_OS patterns
in one run:

  Pattern A — verify+rollback closed loop: the evaluator's candidate fix is
    rejected by the kernel verifier (EVAL_VERIFY_FAIL), rolled back
    (EVAL_ROLLBACK), retried (EVAL_RETRY) and finally accepted (EVAL_ACCEPT).
  Pattern B — kernel semantic cache short-circuit: the retry re-issues the
    same (role, prompt), which hits the cache (CACHE_HIT) and skips the LLM
    call (no PROXY_REQ).

fs.img is regenerated first so /cache.bin starts empty (deterministic). The
written file carries a labelled, observed-count summary using the spaced
phrases the completion gate greps for ("VERIFY FAIL", "ROLLBACK", "RETRY",
"ACCEPT", "CACHE HIT") followed by the raw transcript. Exits non-zero if any
required event was not observed, so the demo can never be silently empty.

Mock-only, no network.
"""
from __future__ import annotations

import os
import pathlib
import re
import subprocess
import sys
import time

ROOT = pathlib.Path(__file__).resolve().parents[1]
sys.path.insert(0, str(ROOT / "host"))

from proxy_pipe import Xv6Channel            # noqa: E402
from proxy_daemon import (                   # noqa: E402
    mock_handler, PROXY_REQ_TAG, PROXY_RES_TAG,
)

OUT = ROOT / "docs" / "patterns_demo.txt"


def regen_fsimg() -> None:
    """Rebuild fs.img so the response cache starts empty."""
    xv6 = ROOT / "xv6-src"
    (xv6 / "fs.img").unlink(missing_ok=True)
    subprocess.run(["make", "fs.img"], cwd=str(xv6),
                   stdout=subprocess.DEVNULL, stderr=subprocess.DEVNULL,
                   check=False)


def drive(timeout_s: float = 30.0) -> list[str]:
    """Run `triage short.log`, service every PROXY_REQ with the mock echo,
    and return the full console transcript (one entry per line)."""
    ch = Xv6Channel()
    transcript: list[str] = []
    try:
        ch.wait_for(b"init: starting sh", timeout=15.0)
        time.sleep(0.2)
        ch.send("triage short.log\n")
        deadline = time.monotonic() + timeout_s
        line = bytearray()
        while time.monotonic() < deadline:
            try:
                chunk = os.read(ch.proc.stdout.fileno(), 4096)
            except BlockingIOError:
                chunk = b""
            if not chunk:
                time.sleep(0.02)
                continue
            for byte in chunk:
                if byte != 0x0A:
                    line.append(byte)
                    continue
                text = bytes(line).decode("utf-8", "replace")
                line.clear()
                transcript.append(text)
                if text.startswith(PROXY_REQ_TAG + "\t"):
                    parts = text.split("\t", 3)
                    if len(parts) == 4:
                        _, req_id, role, prompt = parts
                        reply = mock_handler(role, prompt)
                        ch.send(f"{PROXY_RES_TAG}\t{req_id}\t{reply}\n")
                elif text == "TRIAGE_DONE":
                    return transcript
        return transcript
    finally:
        try:
            ch.proc.kill()
        except Exception:
            pass


def main() -> int:
    regen_fsimg()
    transcript = drive()

    # The xv6 console echoes the host's PROXY_RES bytes (sent on stdin) onto
    # stdout, which can split a concurrent agent's output line mid-token
    # (e.g. "EVAL_VER" + <echoed PROXY_RES> + "IFY_FAIL"). Strip the echoed
    # proxy frames before counting so event tallies are accurate; the raw
    # transcript is still written verbatim below for transparency.
    cleaned = re.sub(r"PROXY_(?:REQ|RES)\t[^\n]*\n?", "",
                     "\n".join(transcript))

    def count(token: str) -> int:
        return cleaned.count(token)

    events = {
        "VERIFY FAIL": count("EVAL_VERIFY_FAIL"),
        "ROLLBACK":    count("EVAL_ROLLBACK"),
        "RETRY":       count("EVAL_RETRY"),
        "ACCEPT":      count("EVAL_ACCEPT"),
        "CACHE HIT":   count("CACHE_HIT"),
    }

    lines = []
    lines.append("=== Liberal_OS two-pattern e2e demo (mock, `triage short.log`) ===")
    lines.append("generated by bench/capture_patterns.py — one run, both patterns")
    lines.append("")
    lines.append("Pattern A — verify+rollback closed loop (kernel verifier guards LLM fixes):")
    lines.append(f"  VERIFY FAIL : {events['VERIFY FAIL']}")
    lines.append(f"  ROLLBACK    : {events['ROLLBACK']}")
    lines.append(f"  RETRY       : {events['RETRY']}")
    lines.append(f"  ACCEPT      : {events['ACCEPT']}")
    lines.append("")
    lines.append("Pattern B — kernel semantic cache short-circuit (skips PROXY_REQ / LLM call):")
    lines.append(f"  CACHE HIT   : {events['CACHE HIT']}")
    lines.append("")
    lines.append("--- raw xv6 console transcript ---")
    lines.extend(transcript)
    lines.append("")

    missing = [k for k, v in events.items() if v == 0]
    OUT.parent.mkdir(parents=True, exist_ok=True)
    OUT.write_text("\n".join(lines), encoding="utf-8")

    if missing:
        sys.stderr.write(f"capture_patterns: missing events {missing}\n")
        return 1
    print("PATTERNS_DEMO_OK " + " ".join(f"{k.replace(' ', '_')}={v}"
                                         for k, v in events.items()))
    return 0


if __name__ == "__main__":
    sys.exit(main())
